import snap

graph = snap.TNGraph.New()
visited = []
for i in range(0, 10):
    visited.append(False)
    graph.AddNode(i)

# == Peterson Graph ==
# graph.AddEdge(0,1)
# graph.AddEdge(0,7)
# graph.AddEdge(0,8)
# graph.AddEdge(1,2)
# graph.AddEdge(1,5)
# graph.AddEdge(2,3)
# graph.AddEdge(2,6)
# graph.AddEdge(3,4)
# graph.AddEdge(3,7)
# graph.AddEdge(4,5)
# graph.AddEdge(4,8)
# graph.AddEdge(5,9)
# graph.AddEdge(6,8)
# graph.AddEdge(6,9)
# graph.AddEdge(7,9)


graph.AddEdge(0,1)
graph.AddEdge(0,3)
graph.AddEdge(0,4)
graph.AddEdge(1,2)
graph.AddEdge(1,3)
graph.AddEdge(2,3)
graph.AddEdge(3,4)

snap.SaveEdgeList(graph, "test.txt", "Graph generated by snap.py for CSE121 Programming Project")